### ISSUE TITLE
Как передавать скидки на заказ

### ISSUE THREAD

**Issue by osben** [rakchaev/tinkoff-merchant-api#3]
Здравствуйте. 
Возник вопрос, как передавать скидки. 
К примеру у заказа может быть скидка в % или статическая. 
Предусмотрены ли такие сценарии ?

**Comment by pinkiesky** [comment]
А в документации к API по этому поводу что-нибудь сказано?

**Comment by osben** [comment]
нету (

**Comment by pinkiesky** [comment]
Функционала скидок нет и в [Android SDK](https://github.com/TinkoffCreditSystems/tinkoff-asdk-android/search?q=discounts&type=Code). Боюсь, расчета скидок нет на уровне API, что логично, т.к. мы оперируем операцией, а не товарами. 

Но! У метода [Init](https://oplata.tinkoff.ru/landing/develop/documentation/Init) есть параметр и объект `Receipt`, в который вы можете "неявно" поместить инф-ию о скидке: если `Price * Quantity != Amount`, то что-то у нас не так (скидка, например). Так делать я не пробовал и, по большому счету, вам не советую, т.к. это больше похоже на костыль. Крайнее решение.

Если честно, вообще не понимаю зачем эти данные в оплату передавать...

**Comment by osben** [comment]
А затем что если строится воронки или формируются чеки\накладные и т.д. то в списке услуг\товаров должна быть реальная цена а ниже указана скидка. 

Вопрос был не в том правильно или нет, а о возможности. 
Как раз что бы работали скидки теперь нужно будет делать костыли и отнимать фактическую скидку от стоимости ед товара. 
спасибо

**Comment by imevro** [comment]
Я бы использовал параметр `DATA`

**Comment by rakchaev** [comment]
Я пробовал добавлять в Items один элемент с отрицательной суммой (скидкой) и названием «Скидка».
Общая сумма и сумма по товарам сходились, но вот в ОФД такой чек не уходил.

Поэтому лучший вариант — отнимать у каждого товара скидку. Т.е. в Price указывать актуальную цену с учетом скидки.
