### ISSUE TITLE
Опубликовать последнюю версию в НПМ

### ISSUE THREAD

**Issue by imevro** [rakchaev/tinkoff-merchant-api#4]
Долгое время не мог понять почему у меня логи через `debug` не работают, оказалось, что версия в репозитории и НПМе отличаются: https://unpkg.com/tinkoff-merchant-api@3.0.0/index.js

**Comment by rakchaev** [comment]
Привет!

Ага, спасибо! Выпустил свежую версию 3.1.0 и залил в npm.
