### ISSUE TITLE
checkNotificationRequest возвращает false: Поменялись IP серверов нотификации? 

### ISSUE THREAD

**Issue by pinkiesky** [rakchaev/tinkoff-merchant-api#5]
В последнее время стали приходить нотификации c `91.194.227.99`. Знает кто-нибудь про эту ситуацию? В новостях (вроде бы) пусто...
Само собой, `checkNotificationRequest` выбрасывает `success: false`.  

Решение1: заменить `notificationIpStart` на `'91.194.22'`.
Решение2: убрать проверку по IP вообще, как по мне, проверка по токену и ключу вполне самодостаточна. 

PS: у себя в продакшене изменил `notificationIpStart`, полет пока нормальный.

**Comment by rakchaev** [comment]
Привет!

Ага, все верно. Раньше было в доке про проверку IP, сейчас в обновленной доке уже нет.
Удалил: c48cd7f012cfa52f7c17e2a4c2c7a5576323cdac
